export const TRANSACTION_CREATE_REQUEST = 'TRANSACTION_CREATE_REQUEST'
export const TRANSACTION_CREATE_SUCCESS = 'TRANSACTION_CREATE_SUCCESS'
export const TRANSACTION_CREATE_FAIL = 'TRANSACTION_CREATE_FAIL'

export const TRANSACTION_LAST_LIST_REQUEST = 'TRANSACTION_LAST_LIST_REQUEST'
export const TRANSACTION_LAST_LIST_SUCCESS = 'TRANSACTION_LAST_LIST_SUCCESS'
export const TRANSACTION_LAST_LIST_FAIL = 'TRANSACTION_LAST_LIST_FAIL'

export const TRANSACTION_ALL_LIST_REQUEST = 'TRANSACTION_ALL_LIST_REQUEST'
export const TRANSACTION_ALL_LIST_SUCCESS = 'TRANSACTION_ALL_LIST_SUCCESS'
export const TRANSACTION_ALL_LIST_FAIL = 'TRANSACTION_ALL_LIST_FAIL'
