export const TRIPS_LIST_REQUEST = 'TRIPS_LIST_REQUEST'
export const TRIPS_LIST_SUCCESS = 'TRIPS_LIST_SUCCESS'
export const TRIPS_LIST_FAIL = 'TRIPS_LIST_FAIL'

export const TRIP_DETAILS_REQUEST = 'TRIP_DETAILS_REQUEST'
export const TRIP_DETAILS_SUCCESS = 'TRIP_DETAILS_SUCCESS'
export const TRIP_DETAILS_FAIL = 'TRIP_DETAILS_FAIL'

export const TRIP_CREATE_REQUEST = 'TRIP_CREATE_REQUEST'
export const TRIP_CREATE_SUCCESS = 'TRIP_CREATE_SUCCESS'
export const TRIP_CREATE_FAIL = 'TRIP_CREATE_FAIL'

export const TRIP_DELETE_REQUEST = 'TRIP_DELETE_REQUEST'
export const TRIP_DELETE_SUCCESS = 'TRIP_DELETE_SUCCESS'
export const TRIP_DELETE_FAIL = 'TRIP_DELETE_FAIL'

export const TRIP_MEMBERS_REQUEST = 'TRIP_MEMBERS_REQUEST'
export const TRIP_MEMBERS_SUCCESS = 'TRIP_MEMBERS_SUCCESS'
export const TRIP_MEMBERS_FAIL = 'TRIP_MEMBERS_FAIL'

export const MEMBER_CREATE_REQUEST = 'MEMBER_CREATE_REQUEST'
export const MEMBER_CREATE_SUCCESS = 'MEMBER_CREATE_SUCCESS'
export const MEMBER_CREATE_FAIL = 'MEMBER_CREATE_FAIL'
export const MEMBER_CREATE_CLEAR_ERROR = 'MEMBER_CREATE_CLEAR_ERROR'

export const MEMBER_UPDATE_REQUEST = 'MEMBER_UPDATE_REQUEST'
export const MEMBER_UPDATE_SUCCESS = 'MEMBER_UPDATE_SUCCESS'
export const MEMBER_UPDATE_FAIL = 'MEMBER_UPDATE_FAIL'
export const MEMBER_UPDATE_CLEAR_ERROR = 'MEMBER_UPDATE_CLEAR_ERROR'
