export const USER_TRIPS_REQUEST = 'USER_TRIPS_REQUEST'
export const USER_TRIPS_SUCCESS = 'USER_TRIPS_SUCCESS'
export const USER_TRIPS_FAIL = 'USER_TRIPS_FAIL'

export const TRIP_DETAILS_REQUEST = 'TRIP_DETAILS_REQUEST'
export const TRIP_DETAILS_SUCCESS = 'TRIP_DETAILS_SUCCESS'
export const TRIP_DETAILS_FAIL = 'TRIP_DETAILS_FAIL'

export const TRIP_MEMBERS_REQUEST = 'TRIP_MEMBERS_REQUEST'
export const TRIP_MEMBERS_SUCCESS = 'TRIP_MEMBERS_SUCCESS'
export const TRIP_MEMBERS_FAIL = 'TRIP_MEMBERS_FAIL'
